# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_room.proto',
  package='chatroom',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63hat_room.proto\x12\x08\x63hatroom\"E\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07reciver\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"\x19\n\x04User\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\x19\n\x08Metadata\x12\r\n\x05limit\x18\x01 \x01(\x05\"\x17\n\x08Response\x12\x0b\n\x03res\x18\x01 \x01(\t2\xdf\x01\n\x08\x43hatRoom\x12\x34\n\x0cRegisterUser\x12\x0e.chatroom.User\x1a\x12.chatroom.Response\"\x00\x12\x32\n\x08ListUser\x12\x12.chatroom.Metadata\x1a\x0e.chatroom.User\"\x00\x30\x01\x12\x34\n\x07SendMsg\x12\x11.chatroom.Message\x1a\x12.chatroom.Response\"\x00(\x01\x12\x33\n\nReceiveMsg\x12\x0e.chatroom.User\x1a\x11.chatroom.Message\"\x00\x30\x01\x42\x32\n\x19io.grpc.examples.chatroomB\rChatRoomProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='chatroom.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='chatroom.Message.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reciver', full_name='chatroom.Message.reciver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='chatroom.Message.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='chatroom.Message.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=98,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='chatroom.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='chatroom.User.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=125,
)


_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='chatroom.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='chatroom.Metadata.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=152,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='chatroom.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='chatroom.Response.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'chat_room_pb2'
  # @@protoc_insertion_point(class_scope:chatroom.Message)
  ))
_sym_db.RegisterMessage(Message)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'chat_room_pb2'
  # @@protoc_insertion_point(class_scope:chatroom.User)
  ))
_sym_db.RegisterMessage(User)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'chat_room_pb2'
  # @@protoc_insertion_point(class_scope:chatroom.Metadata)
  ))
_sym_db.RegisterMessage(Metadata)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'chat_room_pb2'
  # @@protoc_insertion_point(class_scope:chatroom.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031io.grpc.examples.chatroomB\rChatRoomProtoP\001\242\002\003RTG'))

_CHATROOM = _descriptor.ServiceDescriptor(
  name='ChatRoom',
  full_name='chatroom.ChatRoom',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=180,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterUser',
    full_name='chatroom.ChatRoom.RegisterUser',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListUser',
    full_name='chatroom.ChatRoom.ListUser',
    index=1,
    containing_service=None,
    input_type=_METADATA,
    output_type=_USER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='chatroom.ChatRoom.SendMsg',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveMsg',
    full_name='chatroom.ChatRoom.ReceiveMsg',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATROOM)

DESCRIPTOR.services_by_name['ChatRoom'] = _CHATROOM

# @@protoc_insertion_point(module_scope)
